name: build dockers and push to hub

on:
  workflow_dispatch:

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Julia Docker image
        run: docker build . --file docker-julia/Dockerfile --tag learningbydoingdocker/lbd2021-julia-example:latest
      - name: Push Julia Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lbd2021-julia-example
      - name: Build the Python Docker image
        run: docker build . --file docker-python/Dockerfile --tag learningbydoingdocker/lbd2021-python-example:latest
      - name: Push Python Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lbd2021-python-example
      - name: Build the R Docker image
        run: docker build . --file docker-r/Dockerfile --tag learningbydoingdocker/lbd2021-r-example:latest
      - name: Push R Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lbd2021-r-example
